export const PRODUCT_REQUEST="PRODUCT_REQUEST"
export const PRODUCT_FAILURE="PRODUCT_FAILURE"


// post
export const POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS"

// get
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"

// patch
export const PATCH_PRODUCT_SUCCESS="PATCH_PRODUCT_SUCCESS"